return {
    "ability", "absence", "academy", "account", "achievement", "activity", "addition", "adventure", "affection",
    "agency", "agreement", "aircraft", "airline", "airport", "alliance", "amazing", "ambition", "analysis", "ancestor",
    "anxiety", "apology", "appetite", "applause", "appointment", "approval", "argument", "arrival", "artist", "assembly",
    "assessment", "assignment", "assistance", "associate", "assumption", "atmosphere", "attitude", "authority", "backbone",
    "background", "backpack", "balance", "balloon", "bargain", "barrier", "battle", "beach", "beauty", "beginning", "behavior",
    "belief", "benefit", "biology", "birthday", "blessing", "board", "boundary", "brain", "breakfast", "breath", "bridge", "brother",
    "builder", "building", "business", "butterfly", "cabinet", "calendar", "camera", "campaign", "candidate", "capital", "captain",
    "career", "celebration", "challenge", "champion", "character", "charity", "chemistry", "childhood", "choice", "citizen", "classroom",
    "client", "climate", "clothing", "coffee", "collection", "college", "comfort", "command", "committee", "community", "company", "comparison",
    "competition", "complaint", "complex", "component", "concept", "condition", "conference", "confidence", "conflict", "connection", "consequence",
    "construction", "consultant", "contact", "contract", "contrast", "control", "conversation", "cooperation", "courage", "creature", "credit", "crisis",
    "criticism", "culture", "customer", "damage", "danger", "daughter", "decision", "defense", "definition", "delivery", "demand", "department", "departure",
    "dependent", "description", "design", "desire", "destination", "development", "device", "dialogue", "difficulty", "direction", "disaster", "discipline",
    "discovery", "discussion", "disease", "display", "distance", "distribution", "diversity", "document", "driver", "economics", "education", "efficiency",
    "election", "element", "emergency", "emotional", "employee", "employer", "employment", "encouragement", "energy", "engineer", "enterprise", "enthusiasm",
    "environment", "equipment", "establishment", "evaluation", "event", "evidence", "examination", "example", "exchange", "exercise", "exhibition", "existence",
    "expansion", "expectation", "experience", "experiment", "exploration", "expression", "extension", "extraction", "facility", "failure", "faith", "family", 
    "fantasy", "fashion", "feature", "feedback", "festival", "finance", "finding", "fireplace", "flight", "focus", "football", "forecast", "formation", "foundation", 
    "freedom", "friendship", "function", "future", "garden", "garment", "gateway", "generation", "generosity", "genius", "geography", "gesture", "girlfriend", 
    "glory", "goalkeeper", "governor", "graduate", "grammar", "gravity", "guidance", "guitar", "happiness", "harbor", "hardware", "harmony", "headline", "health", 
    "hearing", "heritage", "holiday", "homework", "honesty", "hospital", "household", "housing", "humanity", "hunger", "identity", "illustration", "imagination", 
    "impact", "implementation", "impression", "incident", "income", "independence", "industry", "inflation", "information", "initiative", "innovation", "inspection", 
    "inspiration", "installation", "instrument", "insurance", "intelligence", "interaction", "interest", "interpretation", "interview", "investment", "invitation", 
    "island", "journey", "journal", "judgment", "justice", "keyboard", "kingdom", "knowledge", "laboratory", "landscape", "language", "laughter", "leadership", 
    "learning", "lecture", "legend", "lifestyle", "lightning", "literature", "location", "loyalty", "machine", "magazine", "maintenance", "management", "manufacture", 
    "marketing", "marriage", "material", "mathematics", "measurement", "mechanism", "medicine", "membership", "memory", "message", "metaphor", "military", "ministry", 
    "minority", "miracle", "mixture", "mobility", "moment", "morning", "motion", "motorcycle", "mountain", "movement", "mystery", "nation", "nature", "navigation", 
    "negotiation", "network", "newspaper", "nightmare", "nostalgia", "nutrition", "observation", "occupation", "ocean", "offering", "operation", "opinion", "opportunity", 
    "opposition", "organization", "orientation", "original", "ownership", "package", "painting", "paradise", "participant", "partnership", "passenger", "passion", 
    "patience", "payment", "penalty", "perception", "performance", "permission", "perspective", "phenomenon", "philosophy", "photograph", "physics", "pioneer", 
    "planning", "platform", "pleasure", "poetry", "politician", "population", "position", "possibility", "potential", "poverty", "practice", "preference", "preparation", 
    "presence", "presentation", "president", "pressure", "previous", "principle", "priority", "privacy", "problem", "procedure", "process", "profession", "professor", 
    "progress", "project", "promise", "promotion", "property", "protection", "psychology", "publication", "purpose", "quantity", "quality", "question", "quotation", 
    "reaction", "reality", "reason", "reception", "recipe", "recognition", "recommendation", "recording", "reflection", "reform", "relation", "relationship", 
    "relaxation", "reliability", "religion", "report", "reputation", "requirement", "research", "resolution", "resource", "response", "responsibility", 
    "restaurant", "revolution", "rhythm", "romance", "rotation", "safety", "salary", "salvation", "sanction", "scenario", "schedule", "science", "season", 
    "secretary", "security", "selection", "sensation", "sequence", "settlement", "shadow", "shelter", "shipping", "shortage", "signal", "significance", "simulation", 
    "situation", "skill", "software", "solution", "specialist", "specification", "spectacle", "speech", "sponsor", "sport", "statement", "station", "statistic", 
    "steering", "storage", "strategy", "strength", "structure", "student", "studio", "substance", "success", "suggestion", "supervision", "support", "surgeon", 
    "surgery", "surprise", "survival", "suspicion", "sympathy", "system", "talent", "target", "teacher", "technology", "television", "temperature", "temptation", 
    "tension", "territory", "theater", "therapy", "thesis", "thought", "ticket", "tournament", "tradition", "training", "transaction", "transition", "transport", 
    "travel", "treatment", "triangle", "trust", "universe", "vacation", "validity", "variation", "vehicle", "vessel", "victory", "village", "violence", "virtue", 
    "vision", "visitor", "volcano", "volume", "volunteer", "voting", "voucher", "wealth", "weather", "wedding", "weekend", "welcome", "welfare", "wilderness", 
    "window", "wisdom", "witness", "workshop", "writer", "writing", "yesterday", "youth", "zebra", "zodiac", "zone", "zoo", 
    "action", "adaptation", "advice", "advocate", "agenda", "agriculture", "airline", "alarm", "alcohol", "allegation", 
    "alley", "alliance", "aluminum", "ambassador", "ammunition", "amplitude", "anatomy", "ancient", "angle", "ankle", 
    "apartment", "apparatus", "appeal", "appendix", "approach", "approval", "archer", "architecture", "argument", 
    "arrangement", "arrow", "artillery", "artist", "aspect", "assembly", "assertion", "assignment", "athlete", "attendant",
}
